# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main
      - development
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.ref_name == 'main' || 
      github.ref_name == 'development' || 
      github.ref_name == 'staging'
      
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Set environment from branch
      id: set_environment
      run: |
        echo "ENVIRONMENT=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Show variable
      run: |
        echo "Deploying the site: ${{ vars.APP_URL }}"

    - name: Deploy to ${{ github.event.inputs.environment }}
      run: |
        echo "Deploying to ${{ github.event.inputs.environment }} environment"
        # Your deploy script/commands here
