# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main
      - development
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all tags and history

      - name: Show variable
        run: |
          echo "Deploying the site: ${{ vars.APP_URL }}"

      - name: Get previous tag
        id: prev-tag
        run: |
          if git describe --tags `git rev-list --tags --max-count=1` > /dev/null 2>&1; then
            prev_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "PREV_TAG=$prev_tag" >> $GITHUB_ENV
          else
            echo "PREV_TAG=no_tag_found" >> $GITHUB_ENV

      - name: Generate new tag
        id: new-tag
        run: |
          prev_tag=${{ env.PREV_TAG }}
          if [ "$prev_tag" == "no_tag_found" ]; then
            new_tag="stg-0.0.0"
          else
            IFS='.-' read -r prefix major minor patch <<< "$prev_tag"
            if [ "$patch" -eq 9 ]; then
              new_patch=0
              new_minor=$((minor + 1))
            else
              new_patch=$((patch + 1))
              new_minor=$minor
            fi
            new_tag="${prefix}-${new_minor}.${new_patch}"
          fi
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          new_tag=${{ env.NEW_TAG }}
          git tag $new_tag
          git push origin $new_tag

      - name: Generate changelog
        id: changelog
        run: |
          prev_tag=${{ env.PREV_TAG }}
          new_tag=${{ env.NEW_TAG }}
          if [ "$prev_tag" == "no_tag_found" ]; then
            log=$(git log --pretty=format:"%h - %s (%an, %ad)" HEAD)
          else
            log=$(git log --pretty=format:"%h - %s (%an, %ad)" $prev_tag..HEAD)
          fi
          echo "body=$log" >> $GITHUB_ENV

      - name: Create and publish release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Staging Release ${{ env.NEW_TAG }}
          body: |
            Changes:
            ${{ env.body }}
          draft: false
          prerelease: true

      - name: Deploy to ${{ github.ref_name }} environment
        run: |
          echo "Deploying to ${{ github.ref_name }} environment"
          # Your deploy script/commands here
